
# This is a basic workflow to help you get started with Actions
# Beth


name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - uses: actions/checkout@v1
      - name: Run API Tests
        run: newman run "Restful Booker BVP.postman_collection.json" -e Production.postman_environment.json 
